// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZPiAGBug5SAXfVe1JxcZwvr6SFYEw0k',
    appId: '1:4589728855:web:4973c14caf0deda46a1f12',
    messagingSenderId: '4589728855',
    projectId: 'brainboost-399710',
    authDomain: 'brainboost-399710.firebaseapp.com',
    storageBucket: 'brainboost-399710.appspot.com',
    measurementId: 'G-YPVVTWBQX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASDa6ms6SOkvpN-fep97hgOSUgCroA3Yw',
    appId: '1:4589728855:android:fd49e87215ed90626a1f12',
    messagingSenderId: '4589728855',
    projectId: 'brainboost-399710',
    storageBucket: 'brainboost-399710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNySxbazZro-PfRCz522QP3alSjMr0cUo',
    appId: '1:4589728855:ios:cf5a8bd3c51e41aa6a1f12',
    messagingSenderId: '4589728855',
    projectId: 'brainboost-399710',
    storageBucket: 'brainboost-399710.appspot.com',
    androidClientId: '4589728855-3l6abfmi6igeq1gb42257ese6rgfm1jm.apps.googleusercontent.com',
    iosClientId: '4589728855-6m2s1q1lep2jcfvf33ekgpgdrcqvohsa.apps.googleusercontent.com',
    iosBundleId: 'dev.zierahn.brainboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARAwv5dvAMH8itCKP1srDEg6w6ZI1qYRU',
    appId: '1:4589728855:ios:954500076cfc4be36a1f12',
    messagingSenderId: '4589728855',
    projectId: 'brainboost-399710',
    storageBucket: 'brainboost-399710.appspot.com',
    androidClientId: '4589728855-3l6abfmi6igeq1gb42257ese6rgfm1jm.apps.googleusercontent.com',
    iosClientId: '4589728855-f5rsebn4882aaui502bvhu2lsmr8taki.apps.googleusercontent.com',
    iosBundleId: 'dev.zierahn.braingain',
  );
}
